---
title: "Table 1"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r setup, message = FALSE}
knitr::opts_chunk$set(
    message = FALSE,
    warning = TRUE,
    include = TRUE,
    error = TRUE
)

library(tidyverse)


options(digits = 4, scipen = 999)
```

## tables
```{r}


set.seed(810)
N <- 1000000
pop <- tibble(
  SB = rnorm(N, 5, 2),
  sex = rbinom(N, 1, 0.5),
  mood = rnorm(N, 5, 2) + SB + 2*sex,
)



# 3. Create a Random Sample
random_sample <- sample_n(pop, 140)

# 4. Create a Biased Sample (skews overeducated/conscientious)
high_SB_sample <- pop %>% filter(SB > 4) %>% sample_n(140)



old_table1 <- tribble(
  ~Sample,       ~Measure,                 ~Mean,                          ~SD,
  "Random",      "social belonging",       mean(random_sample$SB) ,          sd(random_sample$SB),     
  "Random",      "mood",                   mean(random_sample$mood),         sd(random_sample$mood),
  "Biassed",     "social belonging",       mean(high_SB_sample$SB) ,         sd(high_SB_sample$SB),     
  "Biassed",     "mood",                   mean(high_SB_sample$mood),        sd(high_SB_sample$mood)
)

new_table1 <- old_table1 %>% 
  bind_cols(tribble(
  ~"Normed mean",                                             ~"Normed SD",
   (mean(random_sample$SB)    -   mean(pop$SB))   / sd(pop$SB),    sd(random_sample$SB)    /   sd(pop$SB),     
   (mean(random_sample$mood)  -   mean(pop$mood)) / sd(pop$mood),  sd(random_sample$mood)  /   sd(pop$mood),     
   (mean(high_SB_sample$SB)   -   mean(pop$SB))   / sd(pop$SB),    sd(high_SB_sample$SB)   /   sd(pop$SB),     
   (mean(high_SB_sample$mood) -   mean(pop$mood)) / sd(pop$mood),  sd(high_SB_sample$mood) /   sd(pop$mood)      
))

old_table1

new_table1 

```

## correlations
```{r}
cor(pop$SB, pop$mood)
```

```{r}
cor(random_sample$SB, random_sample$mood)
```


```{r}
cor(high_SB_sample$SB, high_SB_sample$mood)
```

```{r}
b_normed <- function(x, y, sd_x, sd_y) {

  N <- length(x)
  normed_x <- x/sd_x
  normed_y <- y/sd_y
  

 (N * sum(normed_x * normed_y) - sum(normed_x) * sum(normed_y)) / (N * sum(normed_x^2) - sum(normed_x)^2)
}

b_normed(high_SB_sample$SB, high_SB_sample$mood, sd(random_sample$SB), sd(random_sample$mood,))
```







